/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    kotlin("jvm") version "1.8.10"
    id("application")
}

group = "elevator"
version = "1.0-SNAPSHOT"

// Set Java version to 21 for compatibility
java.sourceCompatibility = JavaVersion.toVersion("21")
java.targetCompatibility = JavaVersion.toVersion("21")

repositories {
    mavenCentral()
}

dependencies {
    implementation(kotlin("stdlib"))

    // JUnit 5 dependencies for unit testing
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.0")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.0")

    // Mockito for mocking
    testImplementation("org.mockito:mockito-core:4.8.0")
}

application {
    mainClass.set("elevator.Main")
}

tasks.jar {
    manifest {
        attributes["Main-Class"] = "elevator.Main"
    }
    from(sourceSets.main.get().output)
}

// Testing configuration using JUnit Jupiter
tasks.test {
    useJUnitPlatform() // This ensures JUnit 5 is used
}

// Java toolchain configuration for Java 21
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21)) // Update to Java 21
    }
}
